/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/scene.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="RootNode" position={[0, -0.319, -1.795]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={2.743}>
        <group name="OfficeChair" position={[0.041, 0, -0.098]} rotation={[-Math.PI / 2, 0, 0]} scale={94.097}>
          <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
          <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
          <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
        </group>
      </group>
      <group name="RootNode002" position={[3.429, 2.37, -3.889]} rotation={[-Math.PI, 0.159, -Math.PI]}>
        <group name="Shelf_Clutter" position={[0.539, 0.238, -0.253]} scale={164.43}>
          <mesh name="Shelf_Clutter_1" geometry={nodes.Shelf_Clutter_1.geometry} material={materials['mat22.005']} />
          <mesh name="Shelf_Clutter_2" geometry={nodes.Shelf_Clutter_2.geometry} material={materials.mat17} />
          <mesh name="Shelf_Clutter_3" geometry={nodes.Shelf_Clutter_3.geometry} material={materials['mat15.002']} />
          <mesh name="Shelf_Clutter_4" geometry={nodes.Shelf_Clutter_4.geometry} material={materials.mat1} />
          <mesh name="Shelf_Clutter_5" geometry={nodes.Shelf_Clutter_5.geometry} material={materials['mat21.004']} />
          <mesh name="Shelf_Clutter_6" geometry={nodes.Shelf_Clutter_6.geometry} material={materials.mat11} />
          <mesh name="Shelf_Clutter_7" geometry={nodes.Shelf_Clutter_7.geometry} material={materials['mat20.001']} />
          <mesh name="Shelf_Clutter_8" geometry={nodes.Shelf_Clutter_8.geometry} material={materials.mat16} />
          <mesh name="Shelf_Clutter_9" geometry={nodes.Shelf_Clutter_9.geometry} material={materials['mat24.001']} />
          <mesh name="Shelf_Clutter_10" geometry={nodes.Shelf_Clutter_10.geometry} material={materials['mat8.002']} />
          <mesh name="Shelf_Clutter_11" geometry={nodes.Shelf_Clutter_11.geometry} material={materials['mat23.005']} />
          <mesh name="Shelf_Clutter_12" geometry={nodes.Shelf_Clutter_12.geometry} material={materials.mat7} />
          <mesh name="Shelf_Clutter_13" geometry={nodes.Shelf_Clutter_13.geometry} material={materials.mat12} />
          <mesh name="Shelf_Clutter_14" geometry={nodes.Shelf_Clutter_14.geometry} material={materials.mat4} />
          <mesh name="Shelf_Clutter_15" geometry={nodes.Shelf_Clutter_15.geometry} material={materials.mat10} />
        </group>
      </group>
      <mesh name="Cube007_Cube008" geometry={nodes.Cube007_Cube008.geometry} material={materials['GrayPlastic.001']} position={[0, -0.287, -3.122]} rotation={[0, -1.564, 0]} scale={1.895}>
        <mesh name="Cube001_Cube002" geometry={nodes.Cube001_Cube002.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cube002_Cube003" geometry={nodes.Cube002_Cube003.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cube003_Cube004" geometry={nodes.Cube003_Cube004.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cube004_Cube005" geometry={nodes.Cube004_Cube005.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cube005_Cube006" geometry={nodes.Cube005_Cube006.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cube006_Cube007" geometry={nodes.Cube006_Cube007.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cube_Cube001" geometry={nodes.Cube_Cube001.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['BlackPlastic.001']} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['BlackPlastic.001']} />
        <mesh name="Cylinder006" geometry={nodes.Cylinder006.geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh name="Cylinder008" geometry={nodes.Cylinder008.geometry} material={materials['BlackPlastic.001']} />
        <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cylinder010" geometry={nodes.Cylinder010.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Cylinder011" geometry={nodes.Cylinder011.geometry} material={materials['BlackPlastic.001']} />
        <mesh name="Cylinder012" geometry={nodes.Cylinder012.geometry} material={materials['WhiteSteelScrew.001']} />
        <mesh name="Cylinder013" geometry={nodes.Cylinder013.geometry} material={materials['BlackCoatSteel.001']} />
        <mesh name="Plane001_Plane002" geometry={nodes.Plane001_Plane002.geometry} material={materials['BlackWood.001']} />
      </mesh>
      <mesh name="group1304172089" geometry={nodes.group1304172089.geometry} material={nodes.group1304172089.material} position={[1.449, 1.912, -3.386]} rotation={[0, 1.57, 0]}>
        <mesh name="group1204213661" geometry={nodes.group1204213661.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group1346465284" geometry={nodes.group1346465284.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group1563047611" geometry={nodes.group1563047611.geometry} material={materials['mat22.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group1692652319" geometry={nodes.group1692652319.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group1896216328" geometry={nodes.group1896216328.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group1911350165" geometry={nodes.group1911350165.geometry} material={materials['mat8.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <group name="group1922886321" position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]}>
          <mesh name="mesh1922886321001" geometry={nodes.mesh1922886321001.geometry} material={materials['mat21.001']} />
          <mesh name="mesh1922886321001_1" geometry={nodes.mesh1922886321001_1.geometry} material={materials['mat22.001']} />
        </group>
        <mesh name="group1929427135" geometry={nodes.group1929427135.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group2141225942" geometry={nodes.group2141225942.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group2146736260" geometry={nodes.group2146736260.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group324829603" geometry={nodes.group324829603.geometry} material={materials['mat22.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group412064894" geometry={nodes.group412064894.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group544821169" geometry={nodes.group544821169.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group562906415" geometry={nodes.group562906415.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group779235197" geometry={nodes.group779235197.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
        <mesh name="group998470600" geometry={nodes.group998470600.geometry} material={materials['mat23.001']} position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]} />
      </mesh>
      <mesh name="group1304172089001" geometry={nodes.group1304172089001.geometry} material={materials['mat23.001']} position={[-1.407, 1.891, -3.367]} rotation={[0, 1.57, 0]}>
        <mesh name="group1204213661001" geometry={nodes.group1204213661001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group1346465284001" geometry={nodes.group1346465284001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group1563047611001" geometry={nodes.group1563047611001.geometry} material={materials['mat22.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group1692652319001" geometry={nodes.group1692652319001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group1896216328001" geometry={nodes.group1896216328001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group1911350165001" geometry={nodes.group1911350165001.geometry} material={materials['mat8.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <group name="group1922886321001" position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]}>
          <mesh name="mesh1922886321002" geometry={nodes.mesh1922886321002.geometry} material={materials['mat21.001']} />
          <mesh name="mesh1922886321002_1" geometry={nodes.mesh1922886321002_1.geometry} material={materials['mat22.001']} />
        </group>
        <mesh name="group1929427135001" geometry={nodes.group1929427135001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group2141225942001" geometry={nodes.group2141225942001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group2146736260001" geometry={nodes.group2146736260001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group324829603001" geometry={nodes.group324829603001.geometry} material={materials['mat22.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group412064894001" geometry={nodes.group412064894001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group544821169001" geometry={nodes.group544821169001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group562906415001" geometry={nodes.group562906415001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group779235197001" geometry={nodes.group779235197001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
        <mesh name="group998470600001" geometry={nodes.group998470600001.geometry} material={materials['mat23.001']} position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]} />
      </mesh>
      <mesh name="Object63" geometry={nodes.Object63.geometry} material={materials.Gray} position={[0.078, 1.454, -2.884]} rotation={[-1.634, 0, 0]} scale={0.05}>
        <mesh name="Object1" geometry={nodes.Object1.geometry} material={materials['Black.001']} position={[3.426, -0.074, 1.173]} scale={0.932} />
        <group name="Object2" position={[3.426, -0.074, 1.173]} scale={0.932}>
          <mesh name="Object2-Mesh" geometry={nodes['Object2-Mesh'].geometry} material={materials.Gray} />
          <mesh name="Object2-Mesh_1" geometry={nodes['Object2-Mesh_1'].geometry} material={materials.ligrey} />
        </group>
        <group name="Object3" position={[3.426, -0.074, 1.173]} scale={0.932}>
          <mesh name="Object3-Mesh" geometry={nodes['Object3-Mesh'].geometry} material={materials.Gray} />
          <mesh name="Object3-Mesh_1" geometry={nodes['Object3-Mesh_1'].geometry} material={materials.ligrey} />
        </group>
        <mesh name="Object31" geometry={nodes.Object31.geometry} material={materials.Gray} />
        <mesh name="Object32" geometry={nodes.Object32.geometry} material={materials.Gray} />
        <mesh name="Object33" geometry={nodes.Object33.geometry} material={materials.Gray} />
        <mesh name="Object34" geometry={nodes.Object34.geometry} material={materials.Gray} />
        <mesh name="Object35" geometry={nodes.Object35.geometry} material={materials.Gray} />
        <mesh name="Object36" geometry={nodes.Object36.geometry} material={materials.Gray} />
        <mesh name="Object37" geometry={nodes.Object37.geometry} material={materials.Gray} />
        <mesh name="Object38" geometry={nodes.Object38.geometry} material={materials.Gray} />
        <mesh name="Object39" geometry={nodes.Object39.geometry} material={materials.Gray} />
        <group name="Object4" position={[3.426, -0.074, 1.173]} scale={0.932}>
          <mesh name="Object4-Mesh" geometry={nodes['Object4-Mesh'].geometry} material={materials.ligrey} />
          <mesh name="Object4-Mesh_1" geometry={nodes['Object4-Mesh_1'].geometry} material={materials.Gray} />
        </group>
        <mesh name="Object40" geometry={nodes.Object40.geometry} material={materials.Gray} />
        <mesh name="Object41" geometry={nodes.Object41.geometry} material={materials.Gray} />
        <mesh name="Object42" geometry={nodes.Object42.geometry} material={materials.Gray} />
        <mesh name="Object43" geometry={nodes.Object43.geometry} material={materials.Gray} />
        <mesh name="Object44" geometry={nodes.Object44.geometry} material={materials.Gray} />
        <mesh name="Object45" geometry={nodes.Object45.geometry} material={materials.Gray} />
        <mesh name="Object46" geometry={nodes.Object46.geometry} material={materials.Gray} />
        <mesh name="Object47" geometry={nodes.Object47.geometry} material={materials.Gray} />
        <mesh name="Object48" geometry={nodes.Object48.geometry} material={materials.Gray} />
        <mesh name="Object49" geometry={nodes.Object49.geometry} material={materials.Gray} />
        <group name="Object5" position={[3.426, -0.074, 1.173]} scale={0.932}>
          <mesh name="Object5-Mesh" geometry={nodes['Object5-Mesh'].geometry} material={materials.ligrey} />
          <mesh name="Object5-Mesh_1" geometry={nodes['Object5-Mesh_1'].geometry} material={materials.Gray} />
        </group>
        <mesh name="Object50" geometry={nodes.Object50.geometry} material={materials.Gray} />
        <mesh name="Object51" geometry={nodes.Object51.geometry} material={materials.Gray} />
        <mesh name="Object52" geometry={nodes.Object52.geometry} material={materials.Gray} />
        <mesh name="Object53" geometry={nodes.Object53.geometry} material={materials.Gray} />
        <mesh name="Object54" geometry={nodes.Object54.geometry} material={materials.Gray} />
        <mesh name="Object55" geometry={nodes.Object55.geometry} material={materials.Gray} />
        <mesh name="Object56" geometry={nodes.Object56.geometry} material={materials.Gray} />
        <mesh name="Object57" geometry={nodes.Object57.geometry} material={materials.Gray} />
        <mesh name="Object58" geometry={nodes.Object58.geometry} material={materials.Gray} />
        <mesh name="Object59" geometry={nodes.Object59.geometry} material={materials.Gray} />
        <mesh name="Object60" geometry={nodes.Object60.geometry} material={materials.Gray} />
        <mesh name="Object61" geometry={nodes.Object61.geometry} material={materials.Gray} />
        <mesh name="Object62" geometry={nodes.Object62.geometry} material={materials.Gray} />
        <mesh name="Object64" geometry={nodes.Object64.geometry} material={materials.Gray} />
        <mesh name="Object65" geometry={nodes.Object65.geometry} material={materials.Gray} />
        <mesh name="Object66" geometry={nodes.Object66.geometry} material={materials.Gray} />
        <mesh name="Object67" geometry={nodes.Object67.geometry} material={materials.Gray} />
        <mesh name="Object30-Mesh" geometry={nodes['Object30-Mesh'].geometry} material={materials.Gray} />
        <mesh name="Object30-Mesh_1" geometry={nodes['Object30-Mesh_1'].geometry} material={materials.darker_grey} />
        <mesh name="Object68-Mesh" geometry={nodes['Object68-Mesh'].geometry} material={materials.Gray} />
        <mesh name="Object68-Mesh_1" geometry={nodes['Object68-Mesh_1'].geometry} material={materials.darker_grey} />
        <mesh name="Object68-Mesh_2" geometry={nodes['Object68-Mesh_2'].geometry} material={materials.ligrey} />
      </mesh>
      <mesh name="ElectricGuitar_mesh" geometry={nodes.ElectricGuitar_mesh.geometry} material={materials.lambert2SG} position={[-3.382, -0.263, -1.53]} rotation={[-1.931, 1.376, 1.911]} scale={0.13} />
      <mesh name="Guitar_Amp" geometry={nodes.Guitar_Amp.geometry} material={materials.lambert3SG} position={[-2.916, 0.432, -3.293]} rotation={[3.135, -0.004, -0.007]} scale={-0.004} />
      <mesh name="e" geometry={nodes.e.geometry} material={materials.lambert3SG} position={[-2.916, 0.432, -3.293]} rotation={[3.135, -0.004, -0.007]} scale={-0.004} />
      <mesh name="d" geometry={nodes.d.geometry} material={materials.lambert3SG} position={[-2.916, 0.432, -3.293]} rotation={[3.135, -0.004, -0.007]} scale={-0.004} />
      <mesh name="c" geometry={nodes.c.geometry} material={materials.lambert3SG} position={[-2.916, 0.432, -3.293]} rotation={[3.135, -0.004, -0.007]} scale={-0.004} />
      <mesh name="b" geometry={nodes.b.geometry} material={materials.lambert3SG} position={[-2.916, 0.432, -3.293]} rotation={[3.135, -0.004, -0.007]} scale={-0.004} />
      <mesh name="a" geometry={nodes.a.geometry} material={materials.lambert3SG} position={[-2.916, 0.432, -3.293]} rotation={[3.135, -0.004, -0.007]} scale={-0.004} />
      <mesh name="group1534886875" geometry={nodes.group1534886875.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group880870465" geometry={nodes.group880870465.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1077533398" geometry={nodes.group1077533398.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1412264498" geometry={nodes.group1412264498.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group992871100" geometry={nodes.group992871100.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1196067630" geometry={nodes.group1196067630.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1126225030" geometry={nodes.group1126225030.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1503710091" geometry={nodes.group1503710091.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1403185431" geometry={nodes.group1403185431.geometry} material={materials['mat22.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1548945793" geometry={nodes.group1548945793.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group2141802031" geometry={nodes.group2141802031.geometry} material={materials['mat22.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group1554736466" geometry={nodes.group1554736466.geometry} material={materials['mat23.002']} position={[-3.356, 0.547, 1.874]} scale={1.503} />
      <mesh name="group177324776" geometry={nodes.group177324776.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group456113812" geometry={nodes.group456113812.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <group name="group2006127357" position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759}>
        <mesh name="mesh2006127357" geometry={nodes.mesh2006127357.geometry} material={materials.mat15} />
        <mesh name="mesh2006127357_1" geometry={nodes.mesh2006127357_1.geometry} material={materials['mat22.003']} />
        <mesh name="mesh2006127357_2" geometry={nodes.mesh2006127357_2.geometry} material={materials.mat5} />
      </group>
      <mesh name="group1401885315" geometry={nodes.group1401885315.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1212375346" geometry={nodes.group1212375346.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group419350030" geometry={nodes.group419350030.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1807297252" geometry={nodes.group1807297252.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group960174394" geometry={nodes.group960174394.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group196578052" geometry={nodes.group196578052.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1334711408" geometry={nodes.group1334711408.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group302394248" geometry={nodes.group302394248.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group2032321183" geometry={nodes.group2032321183.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1179780668" geometry={nodes.group1179780668.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1019592136" geometry={nodes.group1019592136.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1085684984" geometry={nodes.group1085684984.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1326168722" geometry={nodes.group1326168722.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group46364694" geometry={nodes.group46364694.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group333109243" geometry={nodes.group333109243.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group691419308" geometry={nodes.group691419308.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1037969120" geometry={nodes.group1037969120.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group17960853" geometry={nodes.group17960853.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1141373065" geometry={nodes.group1141373065.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1540939634" geometry={nodes.group1540939634.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group765068823" geometry={nodes.group765068823.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1408499295" geometry={nodes.group1408499295.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1211389827" geometry={nodes.group1211389827.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1608359247" geometry={nodes.group1608359247.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1519494874" geometry={nodes.group1519494874.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group690311317" geometry={nodes.group690311317.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1467594704" geometry={nodes.group1467594704.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group904212722" geometry={nodes.group904212722.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group23603136" geometry={nodes.group23603136.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1965762202" geometry={nodes.group1965762202.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group285897109" geometry={nodes.group285897109.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1321801121" geometry={nodes.group1321801121.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group329688719" geometry={nodes.group329688719.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1949694774" geometry={nodes.group1949694774.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1203418331" geometry={nodes.group1203418331.geometry} material={materials['mat23.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group220930692" geometry={nodes.group220930692.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group298275291" geometry={nodes.group298275291.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1698405163" geometry={nodes.group1698405163.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group581341217" geometry={nodes.group581341217.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1915210531" geometry={nodes.group1915210531.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1296981783" geometry={nodes.group1296981783.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1613345632" geometry={nodes.group1613345632.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1968741473" geometry={nodes.group1968741473.geometry} material={materials.mat15} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group2104712147" geometry={nodes.group2104712147.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1500597350" geometry={nodes.group1500597350.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1618286687" geometry={nodes.group1618286687.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group746866220" geometry={nodes.group746866220.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group930438105" geometry={nodes.group930438105.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1732724593" geometry={nodes.group1732724593.geometry} material={materials['mat22.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group247850156" geometry={nodes.group247850156.geometry} material={materials['mat22.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1636848770" geometry={nodes.group1636848770.geometry} material={materials['mat22.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1425606581" geometry={nodes.group1425606581.geometry} material={materials['mat22.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1730487497" geometry={nodes.group1730487497.geometry} material={materials['mat22.003']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1185974778" geometry={nodes.group1185974778.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1975421191" geometry={nodes.group1975421191.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1708989059" geometry={nodes.group1708989059.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group1554701448" geometry={nodes.group1554701448.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="group2039758350" geometry={nodes.group2039758350.geometry} material={materials['mat21.002']} position={[-3.448, 1.371, 2.341]} rotation={[Math.PI, -0.004, Math.PI]} scale={0.759} />
      <mesh name="bigbrr" geometry={nodes.bigbrr.geometry} material={materials.bigbrr} position={[-2.884, 3.012, -3.995]} rotation={[-1.571, -0.004, -3.139]} scale={-2.789} />
      <group name="Modern_rug_Plane004" position={[0.212, -0.327, 1.701]} rotation={[0, 1.552, 0]} scale={0.67}>
        <mesh name="Modern_rug_Plane004-Mesh" geometry={nodes['Modern_rug_Plane004-Mesh'].geometry} material={materials['78909C']} />
        <mesh name="Modern_rug_Plane004-Mesh_1" geometry={nodes['Modern_rug_Plane004-Mesh_1'].geometry} material={materials['455A64']} />
      </group>
      <mesh name="line-up" geometry={nodes['line-up'].geometry} material={materials['line-up']} position={[-3.996, 2.968, 2.496]} rotation={[1.571, -0.002, -1.572]} scale={2.154} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[0.033, 2.512, -3.684]} rotation={[1.66, 0.001, 0.008]} scale={[1.012, 0.888, 0.663]} />
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[0, -0.31, 0]} scale={4} />
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-4.45, 2.564, 0.045]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
