/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ayushcodemate (https://sketchfab.com/ayushcodemate)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-with-2k-textures-450aeb7763dc49d0a176ace339b999ec
Title: Moon With 2K Textures
*/

import React, { useRef } from "react";
import { useGLTF, Text } from "@react-three/drei";

export function Moon(props) {
  const { nodes, materials } = useGLTF("models/moon_with_2k_textures.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.5}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id30_50_0.geometry}
            material={materials.material}
            position={[-0.5, 1, 0.1]}
            scale={0.026}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/moon_with_2k_textures.glb");