/*}
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three"

export function Studio(props) {
  const { nodes, materials } = useGLTF("models/scene3.gltf");
  const texture = useTexture("textures/Baked.jpg");
const textureMaterial = new THREE.MeshStandardMaterial({
  map: texture,
});

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007_Cube008.geometry}
        material={textureMaterial}
        position={[0, -0.287, -3.122]}
        rotation={[0, -1.564, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube002.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_Cube003.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_Cube004.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_Cube005.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_Cube006.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_Cube007.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_Plane002.geometry}
          material={textureMaterial}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1304172089.geometry}
        material={textureMaterial}
        position={[1.449, 1.912, -3.386]}
        rotation={[0, 1.57, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1204213661.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1346465284.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1563047611.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1692652319.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1896216328.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1911350165.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <group position={[0.193, 0, 0]} rotation={[Math.PI, -0.005, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1922886321001.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1922886321001_1.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1929427135.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2141225942.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2146736260.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group324829603.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group412064894.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group544821169.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group562906415.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group779235197.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group998470600.geometry}
          material={textureMaterial}
          position={[0.193, 0, 0]}
          rotation={[Math.PI, -0.005, Math.PI]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1304172089001.geometry}
        material={textureMaterial}
        position={[-1.407, 1.891, -3.367]}
        rotation={[0, 1.57, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1204213661001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1346465284001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1563047611001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1692652319001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1896216328001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1911350165001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <group position={[0.207, 0, 0]} rotation={[Math.PI, -0.006, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1922886321002.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh1922886321002_1.geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group1929427135001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2141225942001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group2146736260001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group324829603001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group412064894001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group544821169001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group562906415001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group779235197001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.group998470600001.geometry}
          material={textureMaterial}
          position={[0.207, 0, 0]}
          rotation={[Math.PI, -0.006, Math.PI]}
        />
      </mesh>
      <group
        position={[0, -0.319, -1.795]}
        rotation={[-Math.PI, 0.01, -Math.PI]}
        scale={2.743}
      >
        <group position={[0.041, 0, -0.098]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OfficeChair_1.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OfficeChair_2.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.OfficeChair_3.geometry}
            material={textureMaterial}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object63.geometry}
        material={textureMaterial}
        position={[0.078, 1.454, -2.884]}
        rotation={[-1.634, 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1.geometry}
          material={textureMaterial}
          position={[0.17, -0.004, 0.058]}
        />
        <group position={[0.17, -0.004, 0.058]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object2-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object2-Mesh_1"].geometry}
            material={textureMaterial}
          />
        </group>
        <group position={[0.17, -0.004, 0.058]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object3-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object3-Mesh_1"].geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object31.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object32.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object33.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object34.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object35.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object36.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object37.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object38.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object39.geometry}
          material={textureMaterial}
        />
        <group position={[0.17, -0.004, 0.058]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object4-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object4-Mesh_1"].geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object40.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object41.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object42.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object43.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object44.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object45.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object46.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object47.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object48.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object49.geometry}
          material={textureMaterial}
        />
        <group position={[0.17, -0.004, 0.058]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object5-Mesh"].geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object5-Mesh_1"].geometry}
            material={textureMaterial}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object50.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object51.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object52.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object53.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object54.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object55.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object56.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object57.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object58.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object59.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object60.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object61.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object62.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object64.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object65.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object66.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object67.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object30-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object30-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object68-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object68-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Object68-Mesh_2"].geometry}
          material={textureMaterial}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ElectricGuitar_mesh.geometry}
        material={textureMaterial}
        position={[-3.382, -0.263, -1.53]}
        rotation={[-1.931, 1.376, 1.911]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Guitar_Amp.geometry}
        material={textureMaterial}
        position={[-2.916, 0.432, -3.293]}
        rotation={[3.135, -0.004, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.e.geometry}
        material={textureMaterial}
        position={[-2.916, 0.432, -3.293]}
        rotation={[3.135, -0.004, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.d.geometry}
        material={textureMaterial}
        position={[-2.916, 0.432, -3.293]}
        rotation={[3.135, -0.004, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.c.geometry}
        material={textureMaterial}
        position={[-2.916, 0.432, -3.293]}
        rotation={[3.135, -0.004, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.b.geometry}
        material={textureMaterial}
        position={[-2.916, 0.432, -3.293]}
        rotation={[3.135, -0.004, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.a.geometry}
        material={textureMaterial}
        position={[-2.916, 0.432, -3.293]}
        rotation={[3.135, -0.004, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1534886875.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group880870465.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1077533398.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1412264498.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group992871100.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1196067630.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1126225030.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1503710091.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1403185431.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1548945793.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2141802031.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1554736466.geometry}
        material={textureMaterial}
        position={[-3.356, 0.547, 1.874]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group177324776.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group456113812.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <group
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2006127357.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2006127357_1.geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh2006127357_2.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1401885315.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1212375346.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group419350030.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1807297252.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group960174394.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group196578052.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1334711408.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group302394248.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2032321183.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1179780668.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1019592136.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1085684984.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1326168722.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group46364694.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group333109243.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group691419308.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1037969120.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group17960853.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1141373065.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1540939634.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group765068823.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1408499295.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1211389827.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1608359247.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1519494874.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group690311317.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1467594704.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group904212722.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group23603136.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1965762202.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group285897109.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1321801121.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group329688719.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1949694774.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1203418331.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group220930692.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group298275291.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1698405163.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group581341217.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1915210531.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1296981783.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1613345632.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1968741473.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2104712147.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1500597350.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1618286687.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group746866220.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group930438105.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1732724593.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group247850156.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1636848770.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1425606581.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1730487497.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1185974778.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1975421191.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1708989059.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1554701448.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group2039758350.geometry}
        material={textureMaterial}
        position={[-3.448, 1.371, 2.341]}
        rotation={[Math.PI, -0.004, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bigbrr.geometry}
        material={textureMaterial}
        position={[-2.884, 3.012, -3.995]}
        rotation={[-1.571, -0.004, -3.139]}
      />
      <group
        position={[3.429, 2.37, -3.889]}
        rotation={[-Math.PI, 0.159, -Math.PI]}
      >
        <group position={[0.539, 0.238, -0.253]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_1.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_2.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_3.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_4.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_5.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_6.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_7.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_8.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_9.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_10.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_11.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_12.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_13.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_14.geometry}
            material={textureMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Shelf_Clutter_15.geometry}
            material={textureMaterial}
          />
        </group>
      </group>
      <group position={[0.212, -0.327, 1.701]} rotation={[0, 1.552, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Modern_rug_Plane004-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Modern_rug_Plane004-Mesh_1"].geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["line-up"].geometry}
        material={textureMaterial}
        position={[-3.996, 2.968, 2.496]}
        rotation={[1.571, -0.002, -1.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={textureMaterial}
        position={[0.033, 2.512, -3.684]}
        rotation={[1.66, 0.001, 0.008]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={textureMaterial}
        position={[0, -0.31, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/scene3.gltf");
