/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: n-malmberg (https://sketchfab.com/n-malmberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-berlin-street-at-night-a5334d969ce64891ba8b19c66f846428
Title: Lowpoly Berlin street at night
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Studio(props) {
  const { nodes, materials } = useGLTF("models/lowpoly_berlin_street_at_night.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="Sketchfab_model"
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={0.625}
      >
        <mesh
          name="Object_2"
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Object_3"
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials["Material.002"]}
        />
        
      
        <mesh
          name="Object_6"
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Material}
        />
        <mesh
          name="Object_7"
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          name="Object_8"
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          name="Object_9"
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          name="Object_10"
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          name="Object_11"
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          name="Object_12"
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          name="Object_13"
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials["beer-texture"]}
        />
        <mesh
          name="Object_14"
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.checker}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/lowpoly_berlin_street_at_night.glb");